### PR TITLE
Some minor updates

### PR DESCRIPTION
**Pull request by iam-py-test**
This adds some tags to my lists (which I forgot last time) and adds the domains version

### CODE REVIEW

**Comment by iam-py-test** [comment]
@collinbarrett thanks for the quick response!

**Comment by collinbarrett** [comment]
I'm in the early phases of work for #372 that we have desperately needed for some time to hopefully make this process easier...

**Comment by iam-py-test** [comment]
> 
> 
> I'm in the early phases of work for #372 that we have desperately needed for some time to hopefully make this process easier...

If that was created, would people like me have to create an account?

**Comment by iam-py-test** [comment]
This is weird:
image
It shows the domains list not existing

**Comment by collinbarrett** [comment]
I can see it. What is your filter in the UI set to?

I filtered on "Name" column to "Malicious website blocklist" and can see the new "(Domains)" variant.

**Comment by iam-py-test** [comment]
> 
> 
> I can see it. What is your filter in the UI set to?
> 
> I filtered on "Name" column to "Malicious website blocklist" and can see the new "(Domains)" variant.

I filtered by _maintainer_. I think I forgot to add I am the maintainer of that list

**Comment by collinbarrett** [comment]
ah. yep. easy to forget.

that's why we need a nice UI form that makes this easier... for sure.

**Comment by iam-py-test** [comment]
> ah. yep. easy to forget.
> 
> that's why we need a nice UI form that makes this easier... for sure.

Can you fix it? I could, but I’d have to open a whole new PR

**Comment by collinbarrett** [comment]
I'd need to do a PR too. I will if/when I have time, but I'm focused on the new UI tool. Captured as an issue so we won't forget.

https://github.com/collinbarrett/FilterLists/issues/2663

**Pull request merged**
