### PR TITLE
support sorting Languages and Software columns

### PR DESCRIPTION
**Pull request by DandelionSprout**
Each time I think that we've surely had to have unearthed every filterlist in existence, we stumble across yet more ones.

I decided to attempt to add sorting for languages and softwares as well, mostly to make it easier for me to keep track of which lists that are missing either of them. Note also that the commit message for that commit was written incorrectly: It's languages and softwares, not languages and tags.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Also, inspired by how 2 of the 3 lists in tonight's pull (as of at the time of writing) use download links, I decided to attempt to take #498 into my own hands as best as I could, by creating a new value called *downloadUrl*. What could possibly go wrong with this.

**Comment by DandelionSprout** [comment]
https://travis-ci.org/collinbarrett/FilterLists/builds/432321665#L878 seems to claim that DownloadButton doesn't exist, despite it clearly being there. So there's that tiny issue to iron out, I guess.

**Comment by DandelionSprout** [comment]
More than 80% of the lists I add, stem from various Issues reports in this repo. But while I look up info on those lists, I sometimes stumble across other lists that they maintain, recommend, or base their lists on, or that show up in Google searches for another list or software tool.

I was pretty tired yesterday, but I'll see what I can do with your requests later today.

**Comment by collinbarrett** [comment]
This PR contains updates for three separate issues. Data, Download Button, and sorting. Still probably best to break it into 3 PRs whenever you have a chance for each issue. That way, I can assist better as needed, and we can pull them in one at a time when they are ready. No rush.

A note: The code causing the merge conflicts in ListsTable now live [here](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/ClientApp/modules/home/components/listsTable/columns/Software.tsx) and [here](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/ClientApp/modules/home/components/listsTable/columns/Languages.tsx). I just did some refactoring breaking apart the ListsTable into separate files for easier maintainability.

**Comment by DandelionSprout** [comment]
I have taken care of the data stuff in the pull I did earlier today. The 'Download Button' stuff I can split up when I feel able to do so, while I'd need to look into whether I should turn the sorting stuff into an Issue or a PR, depending on how well I can understand the new ListsTable folders or not.

**Comment by collinbarrett** [comment]
Could you remove all of the data changes (that I think you already captured in #513) and the download button changes (moved to #517) from this PR so that it only has the sorting changes?

**Comment by DandelionSprout** [comment]
In that case it'd probably be easier to just copy over the changes from https://github.com/collinbarrett/FilterLists/blob/74ded41ed1e8b51b8fc32646f384b64ca39175ec/src/FilterLists.Web/ClientApp/modules/home/components/listsTable/ListsTable.tsx to a new pull. Though since the listsTable has been changed since this pull was originally needed, I don't immediately any reasons to do even that.

**Comment by collinbarrett** [comment]
Ok, up to you. Feel free to just close for now if you want, instead.

Sorry to swap out the ListsTable refactor under your feet, I just think breaking it into smaller pieces is more readable for the future.

I can address the sorting soon, anyway. Part of the reason for my work on #505 is to support showing more columns (some hidden by default with toggles to show) in the ListsTable.

**Comment by DandelionSprout** [comment]
It's perfectly fair that you chose to swap out the refactor, but it'd also mean that this pull couldn't apply to it anymore. So I think I'll close this pull for now.

**Pull request closed without merging**
