### PR TITLE
add unsullied filter

### PR DESCRIPTION
**Pull request by ColumWalsh**
Adding a filter to hide game of thrones spoilers
## Adding or Updating Data?

Please use the the [data model documentation](https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar) to verify your updates conform to project standards.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
My personal recommendation is that setting the viewUrl to 8000 is a bad idea, as they're supposed to be sequential. I very strongly recommend changing it to 1556 if possible.

Once that has been fixed, I can also recommend adding the following to `filterListTag.json`:

```
{
    "filterListId": 1556,
    "tagId": 15
}
```

tagId 15 is for lists that block unconventional things, to show all the diverse things one can in fact do with adblockers.

**Comment by ColumWalsh** [comment]
All good suggestions, I've made the changes you recommend.

**Comment by DandelionSprout** [comment]
Looks great to me now. Now to wait for this repo's owner to get online so he can merge it. Could take up to a day or two at worst.

**Comment by collinbarrett** [comment]
Thanks!

**Pull request merged**
