### PR TITLE
xpi filtelist tag information

### PR DESCRIPTION
**Pull request by troysjanda**

### CODE REVIEW

**Comment by troysjanda** [comment]
Tag id for xpi filterlist

**Comment by collinbarrett** [comment]
This one failed, because it was dependent upon #2358 . You may need to pull the latest from `collinbarrett:master` branch into your `troysjanda:patch-2` branch for this to pass.

**Comment by troysjanda** [comment]
> 
> 
> This one failed, because it was dependent upon #2358 . You may need to pull the latest from `collinbarrett:master` branch into your `troysjanda:patch-2` branch for this to pass.

ok ill have to do this later after work if you want to delete it ill resubmit it later.

**Comment by collinbarrett** [comment]
closing into #2359

**Pull request closed without merging**
