### PR TITLE
Remove Akamaru's lists

### PR DESCRIPTION
**Pull request by stonecrusher**
Akamaru doesn't maintain or provide filterlists anymore.

Kinda unfortunate that `filterListId` is named `id` in FilterList.json.
That's cofusing because `id` in FilterListViewUrl.json is something different.

### CODE REVIEW

**Comment by collinbarrett** [comment]
I’m on vacation, but should be able to review and merge in next 2 weeks. Thanks.

**Comment by stonecrusher** [comment]
Thanks for the notice.
No problem, have a good time! :-)

**Comment by collinbarrett** [comment]
blocked by #2382

**Comment by collinbarrett** [comment]
playing fast and loose. bypassing #2382 to test in production. will rollback from backup if something is broken. 😱

**Pull request merged**
