### PR TITLE
4 lists: anudeepND facebook; Phishing Army; TR-PhishingList URL List; TR-PhishingList IP List

### PR DESCRIPTION
**Pull request by bogachenko**
At the expense of the last list, I am not sure about the correctness of the syntax choice ... I put 9, should I put 15?

### CODE REVIEW

**Comment by bogachenko** [comment]
what the fuck is with codecov? what did I do wrong, why is everything red here?

**Comment by collinbarrett** [comment]
Looks good. Thanks. Codecov is really just for unit test coverage of the app logic itself. It can be ignored for data updates. I'll see if I can figure out a way to hide it on data updates at some point.

**Comment by DandelionSprout** [comment]
I think I'm seeing a problem here. After ID 1458, it suddenly jumps back to 1159 and continues from there on.

So not only was Codecov convenient for this, but it's also causing substantial problems for a pull request that I was planning to make just about now.

**Comment by DandelionSprout** [comment]
Making matters even worse, is that the IDs between 1159 and 1161 were already in use by other lists, so this has basically broken the site building completely.

**Comment by bogachenko** [comment]
@DandelionSprout

>is that the IDs between 1159 and 1161 were already in use by other lists

 my fuck, I did not know.

@collinbarrett Do I need to correct?

**Comment by bogachenko** [comment]
there is no chronological order in numbers. I must make it a rule to check EVERY number before making a pull.

**Comment by collinbarrett** [comment]
Ah. Sorry, ya'll. It was started with #684 when we had to increment an id due to a conflict with another PR on the same day. Too many collaborators is showing weaknesses in this process. But, that's a good problem to have.

**Comment by collinbarrett** [comment]
I'll tidy up any loose ends tonight that ya'll aren't able to fix beforehand to get it all cleaned up. They are supposed to be in the json in order to prevent this issue. I have a flow that allows me to do that automatically pretty easily.

**Pull request merged**
