### PR TITLE
added "Even cleaner news sites" list #663

### PR DESCRIPTION
**Pull request by bogachenko**
"Even cleaner news sites" list #663

### CODE REVIEW

**Comment by bogachenko** [comment]
Fuck .. not there commit. i am retarded

**Comment by bogachenko** [comment]
fuck

**Comment by bogachenko** [comment]
блять

**Comment by bogachenko** [comment]
Hooray!!! I'm not a moron anymore :dancer:

**Comment by collinbarrett** [comment]
lol. not a moron. thanks for contributing.

**Pull request merged**
