### PR TITLE
Adding example entries for most syntaxes

### PR DESCRIPTION
**Pull request by DandelionSprout**
On the presumption that it is possible to add text-based JSON values that don't lead anywhere, I've now added examples for almost all currently known syntaxes.

Hopefully this should resolve whatever questions anyone would have about them. 🙂🎓

### CODE REVIEW

**Comment by DandelionSprout** [comment]
If it however isn't possible to do, then I suppose we'd have to find a way to tie this to another JSON file or something.

**Comment by collinbarrett** [comment]
Awesome! I love this idea! Unfortunately, technically, this would break the current data-load process. While I like the idea of having examples inline right in the json, I think moving them over to the wiki is the best option at the moment. I'll do that real quick and update back here when it's ready.

**Comment by collinbarrett** [comment]
Closing per the updated wiki at the link below. Let me know if you spot any further errors.

https://github.com/collinbarrett/FilterLists/wiki/Syntax

**Comment by DandelionSprout** [comment]
Since the wiki format also supports multi-line examples, which the JSON inline examples had some problems with, I'm submitting two more examples as well.

* Little Snitch:

```
{
 "action": "allow",
 "process": "any",
 "remote-hosts": "example.com"
},
```

* A third example for localhosts hosts, as I realised that there's an IPv6 localhosts address as well.

`::1 example.com`

**Comment by collinbarrett** [comment]
done

**Comment by DandelionSprout** [comment]
New examples, if #721 is accepted:

• Unix-format hosts.deny file
```
ALL: 123.45.67.89
ALL: example.com
```
• RPZ: `example.com  CNAME .`
• BIND: `zone "example.com" { type master; notify no; file "null.zone.file"; };`
• Unbound: `local-zone: "example.com" redirect`
`local-data: "example.com A 0.0.0.0"`

**Comment by collinbarrett** [comment]
Updated. Thanks.
https://github.com/collinbarrett/FilterLists/wiki/Syntax

**Pull request closed without merging**
