### PR TITLE
Update FilterList.json

### PR DESCRIPTION
**Pull request by Prajwal-Koirala**
https://github.com/complexorganizations/content-blocker/blob/main/assets/browser.txt
https://github.com/complexorganizations/content-blocker/blob/main/assets/hosts

https://github.com/complexorganizations/content-blocker

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
+1 Thank you love.
💕❤😘

**Review by collinbarrett — CHANGES_REQUESTED** [review]
Consider adding the link to the actual list to https://github.com/collinbarrett/FilterLists/blob/main/services/Directory/data/FilterListViewUrl.json .

Thanks. I know the current method of adding a list isn't as easy as it could be.

**Comment by Prajwal-Koirala** [comment]
Merge?

**Comment by collinbarrett** [comment]
> Merge?

See my [review comment](https://github.com/collinbarrett/FilterLists/pull/4019#pullrequestreview-1799686477). Without adding a link to the actual list in `FilterListViewUrl.json`, adding the list to the website probably won't be very useful. Once you add that, I can fixup any build failures and complete the PR.

**Comment by Prajwal-Koirala** [comment]
> > Merge?
> 
> See my [review comment](https://github.com/collinbarrett/FilterLists/pull/4019#pullrequestreview-1799686477). Without adding a link to the actual list in `FilterListViewUrl.json`, adding the list to the website probably won't be very useful. Once you add that, I can fixup any build failures and complete the PR.

https://github.com/complexorganizations/content-blocker/blob/main/assets/browser.txt
https://github.com/complexorganizations/content-blocker/blob/main/assets/hosts
https://github.com/complexorganizations/content-blocker

I am not sure where to put the list,

**Review by collinbarrett — DISMISSED** [review]

**Pull request merged**
