### PR TITLE
Tuesday daytime pull, incl. 12 new lists

### PR DESCRIPTION
**Pull request by DandelionSprout**
I **love** the new software dropdown system. So I decided to assign more syntaxes to the softwares in a hurry, e.g. domains for uBlock Origin, etc.

I've also found 12 new lists, most of them from Steven Black's source listings.

### CODE REVIEW

**Comment by collinbarrett** [comment]
Yay! I love the dropdowns too. Disappointed it took me so long to figure them out (using this project as a way to learn basic React, which I did not know at all prior).

**Comment by collinbarrett** [comment]
So, I've never used TPL in IE before. Now that we have that as a "Software", is it silly to have an `ie` "Tag" as well? I'm thinking we can remove the Tag and just use the Software to flag that. But, want to hear your thoughts. Thanks.

**Comment by DandelionSprout** [comment]
I suppose that the `ie` tag could be removed now, now that you mention it.

**Comment by collinbarrett** [comment]
Thanks, just created #434 to capture that.

**Pull request merged**
