### PR TITLE
add FTPiHole Smartphone Ads and Trackers Blocklist

### PR DESCRIPTION
**Pull request by ftpmorph**

### CODE REVIEW

**Comment by collinbarrett** [comment]
Hey, @ftpmorph , I think you'll want to add your list to [FilterList.json](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json) as well. This PR adds tags, but the "check failed" because list ID 2319 doesn't yet exist in FilterList.json.

**Comment by ftpmorph** [comment]
@collinbarrett thanks for letting me know! I think it bugged out because the file is too big to open in GitHub's site. I made a new PR from the fork on my repo and that seems to have put both required files through: https://github.com/collinbarrett/FilterLists/pull/1726

Hopefully this all works, I have a few more interesting lists to add if so.

**Comment by collinbarrett** [comment]
No worries. I just closed your other two PRs and combined and re-ordered your four commits into this single PR. In order for the check to pass, it needs all the data so foreign keys ling up, etc.

Hopefully this check will pass here, then I'll merge.

Thanks for contributing!

**Comment by ftpmorph** [comment]
Oh brilliant. Thanks a lot for helping out a noobie to this whole process!

By the looks of the readme I should only have to download, edit, and merge FilterList to add new lists in the future now that I'm "in the system" so to speak so that's much fewer things for me to break which is always good.

I'll look into adding more in the future once they're of satisfactory quality. 

Cheers for being patient with me as I worked things out :)

**Comment by collinbarrett** [comment]
Sounds good. Yeah, it is regrettably too difficult for new contributors to learn our process. We've had #372 open forever to build an easier method, I just haven't had time to work on it.

**Pull request merged**
