### PR TITLE
Fixes

### LINKED ISSUE #492: incorrect Software linked to filterListIds 223 and 615
## Bug
On some lists there are wrong softwares, for example `Polish Annoyance Filters - Unlocking Right Click` isn't compatible with AdGuard, it's only compatible with uBO and Nano Adblocker, cuz I mostly only use `script:inject` rules, which AdGuard doesn't support. Also `Official Polish Filters for AdBlock, uBlock Origin & AdGuard` rather aren't compatible with DNS66, just like another lists for adblockers :smile:.

### PR DESCRIPTION
**Pull request by hawkeye116477**
#492

### CODE REVIEW

**Comment by DandelionSprout** [comment]
>(...), we just delete the SoftwareSyntax linking AdGuard to the uBlock Origin static syntax. If AdGuard doesn't support the full syntax, it shouldn't be linked. Thoughts? Maybe @DandelionSprout has suggestions as well?

I don't think I have an easy answer for this, as although I have a licence for AdGuard, since I haven't had time to test which kinds of lists that AdGuard supports or not. I haven't yet tested it with stuff like hosts lists, domains lists, or single-IP lists. As such, I've thus far defaulted to assuming that it supports ABP and uBO lists, as I have reason to assume that 80-90% of uBO-formatted lists are supported by AdGuard.

Removing the SoftwareSyntax entry would've not only left AdGuard with only being shown to support ABP lists until further research is done, but also implies that AdGuard doesn't support any uBO-formatted lists at all.

**Comment by DandelionSprout** [comment]
Now that I think about it, I was about to use *Frellwit's Swedish Filters* as an example of a uBO-targeted list that is practically fully supported by AdGuard... but now that I remember that it uses `!#include` tags to load uBO-specific filters, that list's values could potentially even be changed from it being a uBO list to being a regular ABP list.

I need some consideration time on this, including at least one night of sleep.

**Comment by collinbarrett** [comment]
Haha, ok, no problem, thanks.

I am also certainly open to changing the data model somehow if needed. I started with every list has a syntax. Every syntax is supported by one or more softwares. But, it may very well be more complex than that... I really don't want to chop up "uBlock Origin static" into multiple sub-sections supported by different subsets of software, but if that's a reflection of the real-world, maybe that's something we'll need to consider.

**Comment by DandelionSprout** [comment]
One possibility I can come up with, could be to make it so that when a software has been chosen from the software dropdown menu on FilterLists.com, that lists in partially supported syntaxes could be shown at the end of the search results and in a darker nuance of grey.

Examples of such situations are mixed-format (Singular and range) IP lists with uBlock Origin (Example: Firehol Level 1), and uBO-formatted lists with AdGuard and ABP.

**Comment by DandelionSprout** [comment]
But I'm also in favour of chopping up syntaxes that have large variety inside them. I've for instance chose to spin-off Google Hosts and GO Hosts into `Non-localhost hosts`, as those two lists didn't support uBO in any functional capacity, whereas all other hosts files that circulate on the modern internet does.

But if so, that'd leave the question open as to how much functional variety that'd be set as the treshold to spin off a syntax.

**Comment by hawkeye116477** [comment]
Some lists are only for uBO, but there are also lists which uses uBO syntax, but they are also compatible with AdGuard. So I think that rather should be 2 syntaxes, you can call it also => uBlock Origin Static (compatible with AdGuard) and uBlock Origin Static (not compatible with AdGuard). 
Also there are some lists which uses both AdGuard and uBO syntaxes, for example **Polish GDPR-Cookies Filters - Supplement for uBlock & AdGuard** in condition `!#if !ext_ublock` has filters for AdGuard.

**Comment by hawkeye116477** [comment]
`but the list still works fine in the software (no errors) and some of the rules will be applied)`
It's not that easy, **Polish Annoyance Filters - Unlocking Right Click** is only for uBO, it only contains scriptlet injection rules, which doesn't work on AdGuard. Also there are some lists for example **Official Polish Filters for AdBlock, uBlock Origin & AdGuard - Supplement for uBlock** and **Official Polish Filters for AdBlock, uBlock Origin & AdGuard - Supplement for AdGuard**, supplement for uBlock is rather considered only for uBlock, on AdGuard maybe some problems. Also as I previously wrote, one list can be written with both syntaxes. 
Another example => `https://filters.adtidy.org/extension/chromium/filters/14.txt`, this AdGuard Annoyances Filter is only for AdGuard (for Chromium), there is another filter for AdGuard Firefox and another AdGuard Annoyances Filter only for uBO => `https://filters.adtidy.org/extension/ublock/filters/14.txt`.
I have another suggestion, maybe instead of syntaxes, assign directly list to adblockers or remove AdGuard from list, cuz it doesn't have real subscribe, when you click it only import it to user list with no updates if lists aren't available in AdGuard extension.

**Comment by collinbarrett** [comment]
Thanks, @hawkeye116477 

I really wanted to avoid having to support a list of software that each of the ~600 lists supports. Maintaining that datset sounds like a huge undertaking. Adding the syntax layer makes that a bit easier, but I hear what you are saying in that it might not always be that clean. Still pondering...

Captured your comment about AdGuard's support for `abp:` links over in #28 . Since you say it supports the links but they perform an import action rather than a subscribe action, we should change the text on the buttons to reflect that when AdGuard is filtered on.

**Comment by hawkeye116477** [comment]
@collinbarrett > Captured your comment about AdGuard's support for abp: links over in #28 . Since you say it supports the links but they perform an import action rather than a subscribe action, we should change the text on the buttons to reflect that when AdGuard is filtered on.
Yeah, but this apply only to filterlists which aren't on list of all filters in extension.If filterlist is on list of all filters, then it's enabled. But there is also AdGuard App for Windows, which can behave differently, I didn't used it, so I don't know.

**Comment by collinbarrett** [comment]
Yeah, I don't personally use AdGuard much either, but it does seem like its handling of `abp:` links is inconsistent (e.g. [here](https://github.com/collinbarrett/FilterLists/issues/486)). But, in my opinion, if AdGuard for at least one platform supports these style links, we should have them available on FilterLists.com . Just re-naming to "Import" if that's more appropriate.

Does uBO support `ubo:` link syntax for subscribing? If it does, we can certainly change that. I didn't know it could.

**Comment by hawkeye116477** [comment]
@collinbarrett Yes, uBO and Nano supports `ubo:` link syntax for subscribing.

**Comment by collinbarrett** [comment]
Cool. captured in #28

**Comment by hawkeye116477** [comment]
@collinbarrett But of course it also supports `abp:subscribe`, and `ubo:subscribe` was rather created to disable subscribing filterlists for adblockers other than uBO and Nano :smile:.

**Comment by collinbarrett** [comment]
Moving the conversation over to https://github.com/collinbarrett/FilterLists/issues/496 . Will just kind of leave this PR hanging open until we land on a solution. Thanks.

**Comment by collinbarrett** [comment]
Going to go ahead and merge this as it seems like we are leaning towards option 3 in #496.

**Pull request merged**
