### PR TITLE
Adding Better.fyi List into the website

### PR DESCRIPTION
**Pull request by anarki999**
Adding Better.fyi List into the website

### CODE REVIEW

**Comment by bershan2** [comment]
I think @collinbarrett prefers contributions to [lists.json](https://github.com/collinbarrett/FilterLists/blob/master/data/lists.json) because it is the original file, List.csv is derived from it.

**Comment by collinbarrett** [comment]
Hi @bershan2 . Thanks for your note. I'd actually prefer both the json and the csv to be updated at the moment. I am testing using the csv rather than the json since it is easier for more people to update and maps more cleanly to a relational db table.

@anarki999 , if you can add the list to the .json file as well, that'd be great!

**Comment by anarki999** [comment]
@collinbarrett Collin, I have added the link to the .json file too already =P

**Comment by bershan2** [comment]
@collinbarrett Thanks for explanation.

@anarki999 This pull request contains only your original commit with edits to .CSV. You have pushed the .JSON commit to a different branch [patch-1](https://github.com/anarki999/FilterLists/tree/patch-1). You should push this commit to this branch patch-3 (easy with git), or change the merge request source branch (via GitHub website, if it is allowed). In any case, I think it would be a good idea to `squash` two commits into one to make history clear.

**Comment by anarki999** [comment]
Because I do not know there is a .csv file lool..I only noticed the .Json file =P So, that's why.

@bershan2 Thx for the help, btw =P Hope you like my manual list. I will keep improving the list to increase the anti-detecting ability.

**Pull request closed without merging**
