### PR TITLE
More button stuff

### PR DESCRIPTION
**Pull request by DandelionSprout**
Let's see how well this goes, according to Travis.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Okay, so I had to severely reduce my attempts at making better View buttons, seemingly due to strong dependence on ViewButtonGroup (but don't take my word for it). I somehow wasn't even able to change their button classes.

At least my intended changes in two other files have passed the Travis examination.

**Comment by DandelionSprout** [comment]
And while I was at it anyway, I decided to attempt a slightly heavy-handed solution for #743, by copying over and hosting `vendor.css` on GitHub.

**Comment by DandelionSprout** [comment]
The changes I had previously done to `vendor.css` has now been attempted to be moved to `site.css` instead, for the record.

**Comment by DandelionSprout** [comment]
You can probably tell that I'm very new to website coding, but it seems I've got it right-ish now.

**Comment by DandelionSprout** [comment]
It is probably a very significant obstacle that I've only been able to test the date syntaxes in JavaScript forms á la https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat.

**Comment by DandelionSprout** [comment]
Due to what feels like me like countless help guides on the matter that contradict each other, other options are include (but are not limited to):

* [moment(props.updatedDate).utc(date).local().format("l")](https://stackoverflow.com/questions/32540667/moment-js-utc-to-local-time)
* [moment(props.updatedDate).locale().format("l")](https://stackoverflow.com/questions/49852110/get-locale-format-with-momentjs)
* [(props.updatedDate).DateTimeFormat().resolvedOptions().format(date)](https://danielcompton.net/2017/07/06/detect-user-timezone-javascript)

**Comment by DandelionSprout** [comment]
Okay, so I thank you very much for merging this, so that I could get to see how this'd work in practice.

This didn't go as well as I had hoped, but I don't think a full revert is needed, just to have said that; just a polish pull would be needed.

* Internet Explorer could now get past the dreaded "Promise is undefined" error at long last... only for it to make so many complaints about the .js files that even I have to concede that IE support seems like a dead prospect now.
image

* It seems that `Intl.DateTimeFormat` is unsupported by the site's backend, so I'll move on to one of the alternatives in https://github.com/collinbarrett/FilterLists/pull/744#issuecomment-480022045.

**Comment by collinbarrett** [comment]
Thanks, yeah, I haven't had much free time to assist/test. If you are able to submit another PR with your best guess to fix, I'll merge, and we'll go from there. Thanks!

**Comment by DandelionSprout** [comment]
I'll be right on it! 🙂

**Pull request merged**
