### PR TITLE
Total overhaul of several JSON files

### PR DESCRIPTION
**Pull request by DandelionSprout**
After struggling for the nth time with looking up specific licences in `License.json`, I decided to try to implement something I've had in mind for the past 6 months, and which indeed turned out to require disproportionately much work to implement:

A total overhaul of `License.json` and `Syntax.json`, now with de facto categories and sections to make them much easier to look around in!

### CODE REVIEW

**Comment by collinbarrett** [comment]
Oof. Wow, I see what you did there.

I like the end result, but it's a big change. Let me ponder it for a bit.

Did you do this all in a text-editor just with copy/paste? How sure are you that it is relatively error-free? Not trying to challenge all your hard work, it's just a big/risky change and I know if I had done this myself I would have made all kinds of mistakes trying to copy/paste and keep everything consistent.

**Comment by DandelionSprout** [comment]
I used Ctrl+H and "Replace All" quite a lot, and I feel that `License.json` and `Syntax.json` should be almost entirely error-free, though I can't guarantee it 100%.

Honestly, I'm more worried about `SoftwareSyntax.json`, where I may or may not have lost count of which numbers I had converted to which.

**Comment by collinbarrett** [comment]
Ok.

Yeah, we need #372, I know...

I'll review it/think on it for a bit.

Thanks!

**Comment by collinbarrett** [comment]
temporarily rolled this back. production server went down and I suspect this to be the cause. I'll investigate more when I get home and have better access to logs.

**Comment by collinbarrett** [comment]
yeah, reverting that fixed the issue. i'll investigate the logs and update over in #849

**Pull request merged**
