### PR TITLE
Remove duplicate entries (same name, same viewUrl)

### PR DESCRIPTION
**Pull request by pgirolami**
Changes
* 690 = 1488 and 690 is more complete so kept 690 (fixed the syntax id though)
* 692 = 1489 and 692 is more complete
* 1491 = 1492

### CODE REVIEW

**Comment by collinbarrett** [comment]
Thanks! We need to remove the list ID from any of the related .json files as well. The error Travis is [currently showing](https://travis-ci.org/collinbarrett/FilterLists/builds/511026005#L629) means pulling those list ids out of `FilterListMaintainer.json`.

**Comment by pgirolami** [comment]
@collinbarrett I've updated the PR and it now runs !

**Comment by pgirolami** [comment]
Thanks @collinbarrett How often does the site get updated ? It hasn't been updated yet.

**Comment by collinbarrett** [comment]
It usually takes up to 24 hours due to some caching.

**Pull request merged**
