### PR TITLE
Replace some mirrors of StevenBlack's lists

### PR DESCRIPTION
**Pull request by kowith337**
I found this after I've copy something about myself to GitLab, few months ago, I guess.

### CODE REVIEW

**Comment by collinbarrett** [comment]
Currently, FilterLists only supports up to two mirrors. See [here](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Data/Entities/FilterList.cs#L40). I'm not sure there is a huge need to go beyond two, but we can certainly discuss it.

**Comment by bogachenko** [comment]
just delete one of the three mirrors

**Comment by kowith337** [comment]
If it goes that way, I will put `gitlab.com` URL into the same place of `gitcdn.link`

**Comment by collinbarrett** [comment]
Sure, if you want to do that for now, go for it. Eventually, I'd like to maybe make the number of mirror links dynamic. But, that's pretty low-priority. I personally don't have much of a preference on which of the mirror sites is preferred, though I know it has been discussed in other issues/PRs on this repo. Thanks.

**Comment by kowith337** [comment]
I will do, however.

Some lists like MVPS hosts and FadeMind Unchecky are mirrored already, for now is...
- Mirror 1 is from StevenBlack's repo
- Mirror 2 is GitCDN copyback of Mirror 1

What to do next then?

**Pull request merged**
