### PR TITLE
Early September pull

### PR DESCRIPTION
**Pull request by DandelionSprout**
* Added 11 lists, 2 mirrors, and 2 softwares.
* Softdeleted 2 lists.
* Decided to put the new syntax function to the big test, by separating the `(…) IPv4 + IPv6` syntaxes.
* Fixed 4 view links.

### CODE REVIEW

**Comment by collinbarrett** [comment]
I'm looking into the build error...

**Comment by collinbarrett** [comment]
Hmm, not sure why auth is failing. Can you double-check that [this box](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) is checked for this PR?

**Comment by DandelionSprout** [comment]
Indeed it is turned on as usual: 
image

**Comment by collinbarrett** [comment]
Thanks, I must have broken something... 😢

**Comment by collinbarrett** [comment]
🎉

**Comment by collinbarrett** [comment]
bad news is the web build had the same brokenness. now that I fixed it, it found an issue with your change.

> 
> #14 20.90 Failed to compile.
> #14 20.90 
> #14 20.91 ./src/components/softwareCloud/imgs/index.ts
> #14 20.91 Cannot find file './45-AdGuard-for-WindowsMac.svg' in './src/components/softwareCloud/imgs'.

**Comment by collinbarrett** [comment]
Directory Migrate fail seems to be my fault again. Looking...

**Pull request merged**
