### PR TITLE
remove some Notabug mirrors for #624

### LINKED ISSUE #624: 500 internal server error
**wait (and hope) that this will fix the admin of this site**

opera _2018-11-17_131815_notabug org

mirror 2 Dandelion Sprout's list for Google Hit Hider by Domain - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/List%20for%20Chrome%20Personal%20Blocklist

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianList.txt

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites (Domains) - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltreDomains.txt

mirror 2  Dandelion Sprout's Norwegian Filters for Tidier Websites (Hosts version) https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites (Internet Explor) = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites (Little Snitch) - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/LittleSnitchNorwegianList.lsrules

mirror 2 Dandelion Sprout's Redirector List - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/DandelionSproutRedirectorList.json

mirror 2 Dandelion Sprout's Tidy Sami-languages Internet List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/S%C3%A1megiella-interneahttalisttu.txt

mirror 2 Dandelion Sprout's Very Thorough Website Cleaner = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/VeryThoroughWebsiteCleaner.txt

mirror 2 Dandelion Sprout's Website Stretcher - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Dandelion%20Sprout%27s%20Website%20Stretcher.txt

mirror 2 Evidon Unbreaker https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/EvidonUnbreaker.txt

### PR DESCRIPTION
**Pull request by bogachenko**
fix #624

### CODE REVIEW

**Comment by bogachenko** [comment]
what the fuck

**Comment by bogachenko** [comment]
@collinbarrett you can hold off on that removal. until next week

**Comment by bogachenko** [comment]
what for conflicts with a branch?

**Comment by collinbarrett** [comment]
I thought we were still discussing whether to remove them yet or not over in #624 ? I don't have a strong opinion either way.

**Comment by bogachenko** [comment]
@collinbarrett I do not ask to delete. Our northerner still gave an answer. Just wondering why the conflict in the branch.
default

**Comment by collinbarrett** [comment]
Two of the lists you removed mirrors from were removed altogether by @DandelionSprout in #628 . I just fixed (I think) with https://github.com/collinbarrett/FilterLists/pull/627/commits/af8e0feccfe37d299fb9f4793178c0fd8469c85d

**Comment by bogachenko** [comment]
@collinbarrett аааа

**Comment by bogachenko** [comment]
I think the northerner (@DandelionSprout) will be offended at me.

**Comment by DandelionSprout** [comment]
Normally I'd have been negatively puzzled by why this request wasn't simply closed.

But seeing how NotABug haven't been arsed to fix things after some 12 days, which is an inexcusably long time for a Git host, I suppose I can just as well find some other site to replace it with.

**Comment by collinbarrett** [comment]
Yeah, as the links seem to still be unavailable, best to remove for now. Thanks, all.

**Comment by bogachenko** [comment]
@DandelionSprout :slightly_smiling_face:

**Pull request merged**
