### PR TITLE
NeoHosts and StopForumSpam fix #575 #577

### LINKED ISSUE #575: add support for NeoHosts
## Adding or Updating Lists?

https://github.com/neoFelhz/neohosts

https://hosts.nfz.moe/basic/hosts
https://hosts.nfz.moe/full/hosts
and more..

### LINKED ISSUE #577: add support for toxic_domains list
## Adding or Updating Lists?

https://www.stopforumspam.com/downloads

### PR DESCRIPTION
**Pull request by bogachenko**
fix #575
check @neoFelhz

fix #577
there is not a lot. Do you have any other information on StopForumSpam?
@collinbarrett @DandelionSprout

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Description for the two NeoHosts files: *"A Hosts file for free, responsible, and controlled advertising."* (Very loosely translated from "自由、负责、克制 的去广告 Hosts", as seen on https://hosts.nfz.moe, which could be added as the descriptionSourceUrl.

**Comment by DandelionSprout** [comment]
The StopForumSpam list is a domains list and not a hosts file, and therefore its syntaxId should be 2 instead of 1. And if you want a description for it, you can borrow some lines from https://www.stopforumspam.com/'s "What?" paragraph.

StopForumSpam makes explicit use of "All Rights Reserved" licence, which'd normally mean a licenseId of 5, but since FilterLists automatically falls back on All Rights Reserved in case of a missing licenseId anyway, it's merely optional to add it.

**Comment by DandelionSprout** [comment]
I appreciate your effort in making pull requests, and I've added what I've felt that I've been able to add in a hurry. 🙂

**Comment by bogachenko** [comment]
So John Snow, let's slow down

>Very loosely translated from "自由、负责、克制 的去广告 Hosts",

Give me 2 different Chinese titles for the Full and Basic lists

**Comment by DandelionSprout** [comment]
My best attempt at one for Full Hosts, is the pretty long *"Contains all data and is only recommended for obsessive cleaning. Compared to Basic Hosts, Full Hosts additionally blocks the following: JS Miner mining, Baidu group statistics all-weather positioning record, various statistical services (only JS, no shielded console), common download hijacking, 360 and Baidu portions of software downloada, CNNIC root certificate hijacking, and religious content sites such as Falun Gong that may cause discomfort"*, loosely based on https://github.com/neofelhz/neoHosts#full-hosts.

My original description seems to work for Basic Hosts.

**Comment by DandelionSprout** [comment]
List descriptions on FilterLists.com, as well as most list titles, are generally done in English only, in order to be easily understood.

**Comment by bogachenko** [comment]
@DandelionSprout maybe we should wait for this dude @neoFelhz? he will wake up and say

**Comment by bogachenko** [comment]
Bitch Travis, what's wrong

**Comment by bogachenko** [comment]
@DandelionSprout and by the way, thank you very much for your help

**Pull request merged**
