### PR TITLE
Mid-April pull

### PR DESCRIPTION
**Pull request by DandelionSprout**
This may seem at first glance like a small pull, since it only adds 4 new lists, but I did **a lot** of additional polishing of the database.

Takes care of #1442, #1506, and #1510.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Googling the "a foreign key constraint fails" error gives me no relevant info whatsoever. :(

**Comment by gwarser** [comment]
Try double `''` instead of `\'`

**Comment by DandelionSprout** [comment]
Okay, sure thing. I've done that now.

**Comment by collinbarrett** [comment]
That error seems to indicate that maybe one of the lists you removed still has an entry in the FilterListsTags.json file. Sorry the error message doesn't help us figure out which one.

**Comment by DandelionSprout** [comment]
That's the strange thing. I've double- and triple-checked that all mentions of the deleted lists were removed from that file.

**Comment by collinbarrett** [comment]
I'll try to take a look later on today if you can't figure it out. Thanks.

**Comment by DandelionSprout** [comment]
Thanks in advance. This particular error stumped me even more than usual, unfortunately.

**Pull request merged**
