### PR TITLE
Chin choppa chin choppa

### PR DESCRIPTION
**Pull request by bogachenko**
I'm trying to add all this #709 . It's hard. It's long. I'm working. I accept your clues. Point me to mistakes.

@collinbarrett need label `"needs work"`
and by the way, I will have questions about the syntax of many lists, I try to check with your wiki, but sometimes it is difficult to find similar ones in some lists. I will ask about this later. For now, i add all the sheets that fit your description on the wiki.

### CODE REVIEW

**Comment by bogachenko** [comment]
I'll continue tomorrow.

**Comment by collinbarrett** [comment]
Looks good to me. Just let me know when you think you are done enough to close that issue. Determining list syntax can be a challenge. It's not a required field, so just leave syntax off if you can't determine, and we can add it later. Thanks! Good work!

**Comment by bogachenko** [comment]
closes #709 
everything seems to be. @collinbarrett  check me

**Comment by bogachenko** [comment]
remove the label please

**Pull request merged**
