### PR TITLE
Adding list

### PR DESCRIPTION
**Pull request by mtxadmin**
## Adding or Updating Data?

Please use the the [data model documentation](https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar) to verify your updates conform to project standards.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
The build failure does not seem to have been your fault at all; instead the test environment somehow failed to set itself up.

As such, this seems to me to be suitable for merging. (FYI for @collinbarrett)

**Comment by DandelionSprout** [comment]
On another note, since the list consists exclusively of `!#include` embeddings, I personally recommend changing `syntaxId` from 3 to 21, which helps signify that the list can only be loaded in uBlock Origin and Nano Adblocker.

There may also become a data conflict with #765, in which case it'd be great to double-check if the button on the right for giving maintainers branch access is checked, so that Collin can do the needed polishing himself if he wants to do so.

**Comment by mtxadmin** [comment]
Can you change syntaxId and resolve the issue?

**Comment by collinbarrett** [comment]
replaced by #767 with build fix

**Pull request closed without merging**
