### PR TITLE
feat(data): support soft-deleting FilterLists

### LINKED ISSUE #713: soft delete
Related to #710 (to hide lists from the website), but is now (in my eyes) to be approached as a general idea and not as a person-dependent one.

Additionally, #496 proposes boolean values for software syntax support.

### PR DESCRIPTION
**Pull request by collinbarrett**
resolves #713

### CODE REVIEW

**Comment by collinbarrett** [comment]
Now, by adding a key/value to any entry in [FilterList.json](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json) as follows, it will be excluded from the website/API but gives us the opportunity to easily re-add later.

`"isDeleted": true,`

**Comment by DandelionSprout** [comment]
Nice to know. It'll probably come in handy sometime within the next month, but I can't give an exact date as to when.

**Comment by DandelionSprout** [comment]
Although presuming this is primarily meant for #1737 to begin with, it'll be used within 2 weeks.

**Comment by gwarser** [comment]
Entries with `"isDeleted": true,`  are dropped from "compressed" `FilterList.min.json`?

**Comment by collinbarrett** [comment]
@gwarser , We don't have a "compressed" `FilterList.min.json` that I'm aware of. But, this soft delete feature does remove the lists from being shown on the UI which gets its data from this API endpoint. https://filterlists.com/api/v1/lists

**Comment by gwarser** [comment]
I meant minified. And yes, I looked into https://filterlists.com/api/v1/lists in attempt to exclude these marked lists from by downloader script.

**Pull request merged**
