### PR TITLE
Mid-May pull

### PR DESCRIPTION
**Pull request by DandelionSprout**
* Added my 2 newest lists.
* Changed the syntaxId of *All-in-One Customized Adblock List*, as it uses many `:style` entries, which are nowadays known to cause heavy breakage in Adblock Plus.
* Switched 2 languageId-s around.
* Assigned *Web Annoyances Ultralist - CSS Style Modifying Filters* to yourduskquibbles.

### CODE REVIEW

**Comment by collinbarrett** [comment]
Thanks! First PR since I've converted over to Docker and Azure Pipelines. The PR build skipped the test steps (see [here](https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=397)). I think I have corrected the issue, but can't figure out a way to test. If you can make one more change to this PR branch when you have a sec to trigger another build, I'd like to see if it is now resolved. Thanks!

**Comment by DandelionSprout** [comment]
A peculiar request, but sure thing.

**Comment by collinbarrett** [comment]
Nice, now it's working. Thanks! https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=402

**Comment by collinbarrett** [comment]
...buiding in Docker makes developing locally easier for anyone who wants to contribute (see [here](https://github.com/collinbarrett/FilterLists#building-and-running-locally)). it also should speed up the builds and releases, make hosting simpler, and mostly it's a new technology I wanted to learn professionally...

lol, thaniks for appeasing me, and thanks as always for your FilterLists contributions!

**Pull request merged**
