### PR TITLE
Thursday afternoon pull

### PR DESCRIPTION
**Pull request by DandelionSprout**
This pull adds 6 new lists, changes around on a few values, updates the link to 1 list, and attempts to add images for 2 software tools.

I also decided to add two non-contentious parts of #493. I also have to give special thanks to @hawkeye116477 for figuring out that DNS66 was a hosts tool and not an adblock tool, something that had managed to elude me back when I used that app in 2016-17. No wonder I struggled so much to get my personal filters to work with it! 😳

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Should hopefully have been done now.

**Comment by collinbarrett** [comment]
Nice. Your new software icons worked. Thanks!

**Comment by r-a-y** [comment]
@DandelionSprout - Thanks for adding my lists!  Glad that people are finding it useful.

**Comment by DandelionSprout** [comment]
It was the least I could do. 😊 

I both like to sort things and to further the cause of adblocking, and your lists served a sufficiently unique purpose compared to other lists that are out there.

**Pull request merged**
