### PR TITLE
Early March pull 2

### PR DESCRIPTION
**Pull request by DandelionSprout**
Now this is a pretty juicy one.

* Added ~22 lists.
* Added 3½ new tags (The 4th hasn't been filled up with lists yet.)
* Resolved the "Ultimate Hosts Blacklist" clone situation, more or less.
* Attempted to take care of #1430, #1431, #1435, and #1436. 
* Made the names of many 3rd-party domains versions of list correspond to the normal versions' names.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
>*"System.InvalidOperationException: The seed entity for entity type 'FilterListTag' cannot be added because another seed entity with the same key value for {'FilterListId', 'TagId'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values."*

??????????????????????????????????????????????????

I'm not seeing any clone taggings here, so that error is Greek to me.

**Comment by DandelionSprout** [comment]
I give up.

**Comment by collinbarrett** [comment]
There we go.

> The seed entity for entity type 'FilterListTag' cannot be added because another seed entity with the key value 'FilterListId:1973, TagId:35' has already been added.

Maybe double-check there is not a duplicate of `FilterListId:1973, TagId:35`

**Comment by DandelionSprout** [comment]
Ah, that explains it. Thanks!! 👏

**Pull request merged**
