### PR TITLE
Shallas Blacklists

### LINKED ISSUE #410: add Shalla's Blacklists
http://www.shallalist.de/index.html

### PR DESCRIPTION
**Pull request by bogachenko**
fix #410

### CODE REVIEW

**Comment by bogachenko** [comment]
bitch

**Comment by bogachenko** [comment]
So. I'm tired. I will finish when finished

**Comment by collinbarrett** [comment]
Haha, thanks for tackling this one. It's one I've wanted to get indexed for a while, but never had the patience. Just add another comment when it's done. Take your time.

**Comment by bogachenko** [comment]
@collinbarrett Okay, I'll text you when I'm done. However there is 1 question I have. This guy's got his own license, look https://github.com/cbuijs/shallalist/blob/master/COPYRIGHT. How can I choose the license License.json? №7?
Can add (of course not now, I'd go fucking nuts to redo everything) a single number (with a link to your license) under a custom license?

**Comment by bogachenko** [comment]
@collinbarrett So I guess I'm done, I'm not sure. I'm not sure of anything at all, it's hard for me to tell where I am right now.

**Comment by collinbarrett** [comment]
Looks good. Thanks. Yeah, typically if they have a custom license, we just add a new one to the License file and link them all to it. We can do that at a later time. I'm gonna merge.

Good work.

**Comment by Atavic** [comment]
Epic work, @bogachenko :+1:

**Comment by bogachenko** [comment]
@Atavic 
unnamed

**Pull request merged**
