### PR TITLE
Adding six of my newest filter lists

### PR DESCRIPTION
**Pull request by DandelionSprout**
I've been fairly productive when it comes to making filter lists, so I'm hoping to get to add no less than six new lists to FilterLists.

A quick thing to note:

The subscription link for _Dandelion Sprout's Norwegian Filters for Tidier Websites (Internet Explorer)_ (ID: 388) is ideally meant to be like _javascript:window.external.msAddTrackingProtectionList('https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl','Dandelion Sprouts norske filtre - IE-versjonen')_, and not at all like _abp://subscribe?location=https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl_, since Internet Explorer doesn't have any customisable adblockers that I know of, and therefore this list tries to use Internet Explorer's internal JavaScript-based list addition system.

### CODE REVIEW

**Comment by collinbarrett** [comment]
Awesome! Thanks!

Merged, but won't show up on live site until I get https://github.com/collinbarrett/FilterLists/issues/290 resolved. Hopefully will get that done this weekend.

**Comment by jawz101** [comment]
I was looking at some of the lists today and some of your lists are a little goofy.

`Dandelion Sprout's list for Chrome Personal Blocklist | 8 | https://raw.githubusercontent.com/DandelionSprout/adfilt/master/List%20for%20Chrome%20Personal%20Blocklist | A combined domain blocklist for blocking ransomware.`

This one is blocking pinterest.com, dailymail.co.uk,thesun.co.uk,express.co.uk
mirror.co.uk,telegraph.co.uk,foxnews.com,breitbart.com,answers.microsoft.com

At first glance I would think this list is pretty random to recommend to anyone but yourself :/

**Comment by DandelionSprout** [comment]
@jawz101 Citing from that particular list's description on FilterLists.com:

`Here's how this list works. This is a categorised list of URLs that clot up Google search results. The list is designed for use with Personal Blocklist (and its Import function) for Google Search and Google Chrome users, in such a way that it removes search results for the URLs from your Google searches. (…). The list is VERY subjective, so quite a few of you may NOT want to block the results for ALL of these URLs. In that case, simply pick whichever ones from this buffet that you want to block, and paste them into Personal Blocklist. While this list is technically possible to add to adblocker tools, it'd be a very bad idea to do so, since you wouldn't have any control over which URLs you'll be able to block outright or not.`

Additionally, as for why I picked those sites that you listed, I presumed that some people out there could on paper have grown tired of seeing questionable headlines, stolen art (in the case of Pinterest), and/or uninformative attempts at solutions (in the case of Microsoft Answers). And if they haven't, then they are free and able to either not include those entries when pasting them into Personal Blocklist (which is the name of a non-adblocker extension) or to delete or turn them off.

**Comment by jawz101** [comment]
So a subjective list for an obscure browser add-on probably doesn't need to be on a repository of blocklists, no?

**Comment by DandelionSprout** [comment]
Yeah. Right. An "obscure" add-on that only has in excess of 300,000 current users, according to the add-on stores' statistics that by the way are also visible in plain sight in the links above, and which for instance is 8 times more than Nano Adblocker. And it does block things, specifically from appearing in Google search results.

So far today you've ignored multiple descriptions for this list, failed to do any research, and have made accusations that boil down to you being ignorant. You've clearly got up on the wrong side of the bed this morning. 😐

**Comment by jawz101** [comment]
There is a difference between blocking ads and malware traffic versus a suppression list of sites a single person doesn't want to see in Google search results.  I don't understand why you can't handle the critique?  Does it not make sense that the spirit of sharing communal blocklists is consensus?

It blocks a list of a few conservative news sites and Microsoft answers.  I could understand if it followed a theme but it is just a collection of a handful of unrelated sites.

It's simply not useful when this site a supposed to be a resource of widely-used lists.

I have a list of domains I curate to target blocking mobile app ads and trackers but it makes more sense to either keep it to myself or get the changes accepted in a bigger list.  If it was adopted in a bigger list then thousands of people might potentially get the benefit.  As is, though, I don't think it's a list that would get much interest in its own.

**Comment by collinbarrett** [comment]
Hey, ya'll. Thanks for your thoughts and for maintaining lists. The point of FilterLists is to be:

> The independent, **comprehensive** directory of filter and host lists for advertisements, trackers, malware, and annoyances.

All lists are welcome whether they are useful to only a few people for a very niche reason, or widely used by millions.

I'll be the first to admit that FilterLists has a long way to go by way of improving discoverability, scoring, categorizing, filtering, etc. to improve the experience. In its current form, lists that are very niche and that have very low usage seem to be displayed side-by-side with very popular lists with very little indication as to that fact. All things I'd love to improve. It's just finding the time.

Thanks again.

**Pull request merged**
