### PR TITLE
Adding 378 lists

### PR DESCRIPTION
**Pull request by DandelionSprout**
Holy cow, did I hit a goldmine while researching another repo. 🎉

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Ah, so that was why the build was failing. Thanks for spotting it. 👍

**Comment by bogachenko** [comment]
you forgot to delete again

**Comment by DandelionSprout** [comment]
The list with ID 1188 was a phantom resulting from miscopying during my info gathering process, so there's no reason to keep that "list" around. So I removed it in its entirety.

**Comment by bogachenko** [comment]
Yes. I'm catching on. but the remnants of from this list of, too, need to remove

**Comment by DandelionSprout** [comment]
Ah, okay. I hope I've done so now.

**Comment by bogachenko** [comment]
:shipit: ez

**Comment by DandelionSprout** [comment]
I've now also made some small changes in various files, reflecting that my main Norwegian list is now a Nordic list.

**Comment by bogachenko** [comment]
I think @collinbarrett  is dead :disappointed:
he has not been with us for 8 days
default

**Comment by collinbarrett** [comment]
lol. not dead. on vacation for U.S. Thanksgiving holiday and went computer-free. back now, but might take me another day to get caught up. thanks for your patience.

**Comment by bogachenko** [comment]
hell, you're having (americans) thanksgiving now. my fool

**Pull request merged**
