### PR TITLE
Early-mid March pull 1

### PR DESCRIPTION
**Pull request by DandelionSprout**
Let's have this whole situation resolved while no one is noticing.

While I appreciate `#710`'s idea of boolean values, I think that an easier and more permanent solution by now would be to just blackroll (Blackball?) the guy instead of trying to put a thin cloak on him. I've turned the idea about boolean values into a separate issue report that is non-person-dependent.

One thing is to mess up licences, which in my eyes is fairly forgiveable, given how even I have had to take some shortcuts in the past before I had properly transformed material from parts of 2 or 3 lists into their own independent artistical objects¹. But him refusing to honour credit requests, that's the part that really irks me.

¹ = Full disclosure for purely historical purposes:

* My Nordic list originally contained most entries from [Norsk Adblockliste](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_120_NorskAdblockliste/filter.txt). I skipped the attribution part as I hoped he wouldn't notice (which he didn't), and because his entries only made up 20% of my then-new list at the time. After I later sifted out 75% of his entries as being non-working, I've felt that my list was now sufficiently independent from his list anyway.
* *Staying on the Phone Browser* ended up borrowing ~400 entries from *AdGuard Annoyances*. To that effect, my list had a line where it credited, named, and praised the latter list, which I hoped would iron out any potential fine details about licences. Recently I converted many of those borrowed entries to use wildcard URLs and uBO syntaxes, after which point the credit line was dropped.
* I maintain a mirror of [Adblocking Open Filter JP](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AncientLibrary/Adblocking%20Open%20Filter%20JP), as it is an old and previously lost list. Although it expressly says it is All Rights Reserved, it does list the conditions for redistributing the source code, which I hope that I've met.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
>I'm not sure I love having the note in the README, but we'll go ahead and add it for a time. I may remove it after awhile, as I'd rather not attract too much attention to the issue.

I figured it'd be a way to prevent people from submitting the same lists again in the future, and to tell those people the reasons for it. If you know of a better way to do so, then feel free to implement it.

**Comment by DandelionSprout** [comment]
And also I submitted that note to the "Contributing" guidelines, and not to the main Readme, if that makes the note easier to swallow.

**Comment by DandelionSprout** [comment]
The problem now is that the GitHub frontpage feed for the recentmost edit to the repo shows `remove DMCA-d CHEF-KOCH (#711)`, as that's exactly the kind of info that I hoped wouldn't be too broadly announced, in case he were to resume his insane inquisition against something of some sort.
image

**Comment by DNSCrypt-Lists** [comment]
It's on my feed as well; though I can likely remove it. That or push it away with "noise".

**Comment by DandelionSprout** [comment]
It's not on the front page of FilterLists' GitHub repo anymore, so I feel that it's good enough for now already.
image

**Comment by DNSCrypt-Lists** [comment]
I cannot rid my feed of it; on the other hand I believe I've his attention for now...

**Pull request merged**
